### ISSUE TITLE
Sintesis de calidad_Abigail Coronel

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-abicoronel#1]
[Síntesis sobre la gestión de la calidad en proyectos de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-abicoronel/files/12704162/Sintesis.sobre.la.gestion.de.la.calidad.en.proyectos.de.software.pdf)

**Comment by Aricel117** [comment]
Calif: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
